config/routes.rb
Rails.application.routes.draw do
  get 'stages/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "timelines#index"
  
  resources :timelines do
    resources :stages
  end
  
end

app/models/stage.rb
class Stage
  include Mongoid::Document
  field :stagename, type: String
  field :scenario, type: String
end

app/models/timeline.rb
class Timeline
  include Mongoid::Document
  field :timelinename, type: String
  embeds_many :stages
  accepts_nested_attributes_for :stages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: [:show, :edit, :update, :destroy]
  
  def new
    @timeline = Timeline.find(params[:timeline_id])
    @stage = Stage.new
    #@timeline.build_stage
  end
  
  def create
      @timeline = Timeline.find(params[:timeline_id])
      @timeline.stages << Stage.new(stage_params)
      respond_to do |format|
        if @timeline.save
          format.html { redirect_to timeline_path(@timeline), notice: 'Stage saved' }
        else
          format.html { redirect_to new_timeline_stage_path, notice: 'Oops!' }
        end
      end
    end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end
  
   # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
      params.require(:stage).permit(:stagename, :scenario)
    end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :set_timeline, only: [:show, :edit, :update, :destroy]
  
  def index
    @timelines = Timeline.all
  end
  
  def new
    @timeline = Timeline.new
  end
  
  def show
  end
  
  # POST /meetings
  def create
    @timeline = Timeline.new(timeline_params)

    respond_to do |format|
      if @timeline.save
        format.html { redirect_to @timeline, notice: 'Timeline was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeline
      @timeline = Timeline.find(params[:id])
    end
  
   # Never trust parameters from the scary internet, only allow the white list through.
    def timeline_params
      params.require(:timeline).permit(:timelinename)
    end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Time Travel Testing Tool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

app/views/stages/new.html.erb
<h1>Add a new stage</h1>
<%= simple_form_for([@timeline, @stage]) do |f| %>
    <%= f.input :stagename %>
    <%= f.input :scenario, as: :text %>
    <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/timelines/index.html.erb
<h1>Timelines</h1>

<ul>
<% @timelines.each do |t| %>
    <li><%= t.timelinename %></li>
<% end %>
</ul>

<div class="row ">
  <div class="col-md-12">
    <%= button_to "New timeline", new_timeline_path, method: :get, class: "btn btn-primary" %>
  </div>
</div>

app/views/timelines/new.html.erb
<h1>Add a new timeline</h1>
<div class="row ">
  <div class="col-md-12">
    <%= simple_form_for @timeline do |f| %>
        <%= f.input :timelinename, label: 'Timeline name' %>
        <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/timelines/show.html.erb
<h1>Timelines</h1>
<%= @timeline.timelinename %>
<div class="row ">
  <div class="col-md-12">
   <%= button_to 'Add stage', new_timeline_stage_path(@timeline, @hstage), class: "btn btn-sm btn-success", method: :get %>
  </div>
</div>